services:
  myapp-main: #- this is the container we wanna run as a service
    # the img has my username/ the img name / as well the tag latest which is for dev use
    image: thelostmrj/golftouranmentapp:latest
    ports:
      - 8080:8080 # maps from my local 8080 to the containers port 8080
    environment:
#      - spring.datasource.url=jdbc:mysql://aws-gold-db.cb8yciysq166.us-east-1.rds.amazonaws.com:3306/golfdb
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/golfdb
      - spring.datasource.password=Keyin2024
      - spring.datasource.username=root


